export const LOADING_START: "LOADING_START" = "LOADING_START";
export const LOADING_END: "LOADING_END" = "LOADING_END";
export const SHOW_MESSAGE: "SHOW_MESSAGE" = "SHOW_MESSAGE";
export const HIDE_MESSAGE: "HIDE_MESSAGE" = "HIDE_MESSAGE";
export const SIGN_IN_SUCCESS: "SIGN_IN_SUCCESS" = "SIGN_IN_SUCCESS";
export const LOAD_USER_DATA: "LOAD_USER_DATA" = "LOAD_USER_DATA";
export const LOAD_USER_DATA_SUCCESS: "LOAD_USER_DATA_SUCCESS" =
  "LOAD_USER_DATA_SUCCESS";
export const LOGOUT: "LOGOUT" = "LOGOUT";
export const LOGOUT_SUCCESS: "LOGOUT_SUCCESS" = "LOGOUT_SUCCESS";
