export const LOADING_START: "LOADING_START" = "LOADING_START";
export const LOADING_END: "LOADING_END" = "LOADING_END";
export const SHOW_MESSAGE: "SHOW_MESSAGE" = "SHOW_MESSAGE";
export const HIDE_MESSAGE: "HIDE_MESSAGE" = "HIDE_MESSAGE";
export const SIGN_IN_SUCCESS: "SIGN_IN_SUCCESS" = "SIGN_IN_SUCCESS";
