export const ADD_TASK: "ADD_TASK" = "ADD_TASK";
export const CHANGE_FILTER: "CHANGE_FILTER" = "CHANGE_FILTER";
export const CHANGE_TASKS_STATUSES: "CHANGE_TASKS_STATUSES" =
  "CHANGE_TASKS_STATUSES";
export const DELETE_TASK: "DELETE_TASK" = "DELETE_TASK";
export const DELETE_COMPLETED_TASKS: "DELETE_COMPLETED_TASKS" =
  "DELETE_COMPLETED_TASKS";
export const CHANGE_STATUS_TASK: "CHANGE_STATUS_TASK" = "CHANGE_STATUS_TASK";
export const EDIT_TASK_VALUE: "EDIT_TASK_VALUE" = "EDIT_TASK_VALUE";

export const LOAD_TASKS: "LOAD_TASKS" = "LOAD_TASKS";
export const LOADING_TASKS_SUCCESS: "LOADING_TASKS_SUCCESS" =
  "LOADING_TASKS_SUCCESS";

export const UPDATE_TASKS: "UPDATE_TASKS" = "UPDATE_TASKS";
